stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Running build step"

test-code-job1:
  stage: test
  script:
    - echo "Test 1"

test-code-job2:
  stage: test
  script:
    - echo "Test 2"
